### ISSUE TITLE
IfcSectionedSolidHorizontal and  Directrix 

### ISSUE THREAD

**Issue by BernhardWehrle** [buildingSMART/Sample-Test-Files#100]
Hi all

To which entity must I set the relation "Directrix" 
in the entity "IfcSectionedSolidHorizontal" in Ifc4x3RC2. 
I think i should not use IfcAlignmentCurve because it obsolate.

![IfcSectionedSolidHorizontal ](https://user-images.githubusercontent.com/38724767/105818553-5d114980-5fb7-11eb-8f84-10cc6dda5962.png)

**Comment by SergejMuhic** [comment]
Hi Bernard,

do you want to test sweeping along an alignment or would it be enough to test along any curve? I would propose a more generic curve for now just to test the concept itself because sweeping has not yet been finalized in RC2.

**Comment by pjanck** [comment]
Hi Bernhard,

you are correct, `IfcAlignmentCurve` should not be used anymore. 

Following the comment from Sergej, if you're using a simple line, it should be enough to check the concept of 3D swept geometry.  The concept is not finalized, so there is no definitive answer yet to give. We still have open issues as to "what does sweeping along a `IfcGradientCurve` mean".

In my opinion, one would link `IfcGradientCurve` if you're sweeping along 3D, or `IfcCompositeCurve` if you're sweeping along 2D.

**Comment by BernhardWehrle** [comment]
Hi Stefan

for the unit test IfcCourse  I will set the link to IFCCOMPOSITECURVE

#33 = IFCCOMPOSITECURVE((#39), $);
#52 = IFCSECTIONEDSOLIDHORIZONTAL(#33, (#54, #58), (#53, #57), $);

In the future will it be possible to set a link to the semantic part of the alignment?






AKG Software Consulting GmbH
Bernhard Wehrle
Entwicklung

Uhlandstraße 12
79423 Heitersheim
Germany

Tel.: +49 (0)7634 5612-0
Fax: +49 (0)7634 5612-300
E-Mail: wehrle@akgsoftware.de
Internet: www.akgsoftware.de<http://www.akgsoftware.de>

Geschäftsführer: Dipl.-Ing. Artur K. Günther, Dipl.-Ing. Arno Brüggemann, Dipl.-Ing. (FH) Bernhard Feser, Dipl.-Ing. Jens Günther
Sitz der Gesellschaft: Heitersheim, HRB 310383 (Amtsgericht Freiburg)


________________________________
Von: Stefan Jaud <notifications@github.com>
Gesendet: Dienstag, 26. Januar 2021 09:51
An: buildingSMART/Sample-Test-Files <Sample-Test-Files@noreply.github.com>
Cc: Bernhard Wehrle <wehrle@akgsoftware.de>; Author <author@noreply.github.com>
Betreff: Re: [buildingSMART/Sample-Test-Files] IfcSectionedSolidHorizontal and Directrix (#100)



Externe E-Mail: Vorsicht beim Öffnen von Anhängen und Klicken auf Links!



Hi Bernhard,

you are correct, IfcAlignmentCurve should not be used anymore.

Following the comment from Sergej, if you're using a simple line, it should be enough to check the concept of 3D swept geometry. The concept is not finalized, so there is no definitive answer yet to give. We still have open issues as to "what does sweeping along a IfcGradientCurve mean".

In my opinion, one would link IfcGradientCurve if you're sweeping along 3D, or IfcCompositeCurve if you're sweeping along 2D.

**Comment by TLiebich** [comment]
>In the future will it be possible to set a link to the semantic part of the alignment?

no, this is not planned (at least not directly), any geometric representation should be computable purely from its geometric definition. An open question: should we plan to have an INVERSE backpointer from the resulting curve to its hor/ver alignment definition in the semantic part.

**Comment by jmirtsch** [comment]
> no, this is not planned (at least not directly), any geometric representation should be computable purely from its geometric definition. An open question: should we plan to have an INVERSE backpointer from the resulting curve to its hor/ver alignment definition in the semantic part.

I would support the inverse attribute for this, similar to IfcLinearPositioningElement attribute for axis.  I'm not sure if it makes sense to change the base class for vertical and horizontal alignments (and cant) to to IfcLinearPositioningElement to reuse this attribute.

**Comment by pjanck** [comment]
Opinion: introduce a new Inverse, do not change the base class.

**Comment by pjanck** [comment]
Closing, since the discussion moved to other repository.
