### ISSUE TITLE
Merged #83 by mistake. One error needs to be fixed.

### ISSUE THREAD

**Issue by larswik** [buildingSMART/Sample-Test-Files#102]
A mistake is still in the alignment file for unit test https://github.com/buildingSMART/Sample-Test-Files/tree/master/IFC%204.3/UT_Alignment_12d_11 that was merged by me by mistake.

`IfcPositioningElement` (meaning also all IfcAlignment-s) requires a position according to the express schema. See WHERE rule HasPlacement.

```
ENTITY IfcPositioningElement
 ABSTRACT SUPERTYPE OF(ONEOF(IfcGrid, IfcLinearPositioningElement, IfcReferent))
 SUBTYPE OF (IfcProduct);
 INVERSE
  ContainedInStructure : SET [0:1] OF IfcRelContainedInSpatialStructure FOR RelatedElements;
  Positions : SET [0:?] OF IfcRelPositions FOR RelatingPositioningElement;
 WHERE
  HasPlacement : EXISTS(SELF\IfcProduct.ObjectPlacement);
END_ENTITY;
```
This needs to be fixed. A (0.,0.,0.) placement with east/north direction should suffice.

**Comment by pjanck** [comment]
@LeeGregory12d : what is the status on this file?

**Comment by LeeGregory12d** [comment]
A new Ifc file has been uploaded.
The is only the ViewDefinition error in KIT.
However the IfcAlignment.Axis has been fudged as this is compulsory.
