### ISSUE TITLE
Examples UT_DrainageSystem

### ISSUE THREAD

**Issue by arch1501** [buildingSMART/Sample-Test-Files#109]
I have loaded the UT_DrainageSystem examples in FZKViewer and have not found any pipe and duct instances. 
Should this elements part of the example files?

**Comment by pjanck** [comment]
@arch1501 : can you please provide:

- a screen dump of what you manage to import?
- a link to the exact file you've imported?

I believe this would help troubleshoot the problem a bit easier.

**Comment by arch1501** [comment]
UT_DrainageSystem_1_4.JPG shows pipes and ducts, but the LandXML file contains no such elements.

**Comment by larswik** [comment]
I got the following answer from Juha H: 
_I checked UT_DrainageSystem_1_1.xml and it seems to contain the 6 pipes and 7 structs shown in  UT_DrainageSystem_1_4.JPG. And quite positively, Jon got those alright from that file.
Maybe they loaded the wrong file (UT_DrainageSystem_1_2.xml)?_

**Comment by arch1501** [comment]
Sorry, that was my mistake. I had the wrong file.
