### ISSUE TITLE
Sample testfile with GPS coordinates

### ISSUE THREAD

**Issue by Mannshoch** [buildingSMART/Sample-Test-Files#122]
Customer asked if it's possible to work with GPS Coordinates. I would like to test this case and may report it to the company that delivers us the Software we use to handle IFC. 
Do you have a Sample file with GPS coordinates?

**Comment by pjanck** [comment]
Do you mean a single GPS coordinate specifying the base point of the model, or that all geometry is in GPS coordinates?

**Comment by TLiebich** [comment]
GPS is a spherical coordinate system - longitude, latidute and elevation - but the mapping into a geographic coordinate system has to rely on a map coodinate system - Cartesian with Northing, Easting, Elevation. So GPS coordinates cannot be used directly, only as a reference.

**Comment by Mannshoch** [comment]
@pjanck A single GPS coordinate for the base point. 
@TLiebich Thanks for the details.

That's no problem. I simply need a Test file where the GPS coordinate is correctly set. Whenever we users wish to create an Enhancement request we have to provide sample files. I'm no professional in using IFC but more and more people ask for IFC or provide IFC as exchange file and I try to push the company behind the software we use to enhance the IFC support.

**Comment by pjanck** [comment]
You can provide a single point for reference in `IfcSite`'s attributes `RefLatitude`, `RefLongitude` and `RefElevation`.

An example would be [here](https://github.com/buildingSMART/Sample-Test-Files/blob/master/IFC%202x3/Duplex%20Apartment/Duplex_A_20110907.ifc):

![grafik](https://user-images.githubusercontent.com/59165496/132357519-4a6c167b-cda0-43f1-8501-4e8b70b6467e.png)

**Comment by Mannshoch** [comment]
Can you tell me here what GPS coordinate is set here? I do not understand how to read this line.

**Comment by pjanck** [comment]
Lat = 41 degrees 52 minutes 27.84 seconds
Lon = -87 38 21.84 (similar units)
Elev = -0
