### ISSUE TITLE
No database found error for majority of projects

### ISSUE THREAD

**Issue by AlexParamonov** [buildingSMART/Sample-Test-Files#127]
Hello,

I am exploring the `.ifc` format and trying to get a few demo projects running locally. Unfortunately for the majority of files in this repo, i get a `NULL` database error. Do I need to use any specific viewer or configure the Open IFC Viewer somehow to use files from this repository? Would appreciate a recommendation for another editor if that could solve the problem.

Thank you.

<img width="593" alt="Screenshot 2022-11-28 at 11 47 16" src="https://user-images.githubusercontent.com/352030/204259513-2460bf80-6438-457b-8e83-6dd1dfdb066e.png">

**Comment by peterrdf** [comment]
Hello,

Please try https://rdf.bg/download/ifcviewer-20221128.zip, it is IFC4.3 Add1 compatible for all geometrical representations (and backwards compatible to IFC4.3 and IFC4.3 TC1). You can compile it yourself with Visual Studio 2022 or run it directly from the \ifcviewer\x64\Release directory

Best regards,

Peter.

**Comment by AlexParamonov** [comment]
Thanks, that helped!
