### ISSUE TITLE
Addig 4.3 sample files with IFC4 RV to see picture

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/Sample-Test-Files#17]
Can IFC4.3 files be accompanied with IFC4 RV equivalent to see expected results?
jpeg gives only one view position

**Comment by pjanck** [comment]
Yes, of course. You can also include multiple jpegs if you see fit. Or both. You should add anything that allows the other party to understand what should be there.

**Comment by pjanck** [comment]
Adding this to FAQs -> 6196ad33 .
