### ISSUE TITLE
[PROPOSAL] IFC4.3 Georef UT

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/Sample-Test-Files#18]
I would split the GeoRef_1 unit test into two UT, in order to have a smaller "_1" test with only the GeoRef entities, and another that includes project structure, local placement, shape representation and denote its dependencies to other (still coming) unit tests.

See #16 , the .ifc file would be cut off at line 42 (no entities with id=32 or above). The second UT would include the whole file.

**Comment by SergejMuhic** [comment]
In my opinion, the file is quite manageable. Why would you like to split it up? To be consistent with other test files?

**Comment by pjanck** [comment]
To split the dependencies. So the `_2` georef UT would be dependant on project structure, local placement etc., but the `_1` wouldn't.

**Comment by SergejMuhic** [comment]
Why is this importantß
