### ISSUE TITLE
Missing Test Files for IFC 4x1

### ISSUE THREAD

**Issue by Noranius** [buildingSMART/Sample-Test-Files#30]
Building smart explains 'The latest version, IFC 4.1 is recommended for all current developments [...]' [1]. Hence, it is desirable to offer some test files for IFC 4x1.

[1] https://technical.buildingsmart.org/standards/ifc/ifc-schema-specifications/

**Comment by pjanck** [comment]
Have you had a look at [the official examples](https://standards.buildingsmart.org/IFC/RELEASE/IFC4_1/FINAL/HTML/link/annex-e.htm)?

These have some (minor) mistakes in them, though. I've corrected some of them [here](https://github.com/tumcms/Open-Infra-Platform/tree/development/testdata/IFC4x1ExampleFiles/official) and [here](https://github.com/tumcms/Open-Infra-Platform/tree/development/UnitTests/Schemas/IFC4X1). Hopefully this helps.

**Comment by Noranius** [comment]
Ah ok. Nevermind 👍
