### ISSUE TITLE
UT_Tin_1_Simple_tin.ifc geometry does not match PNG

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/Sample-Test-Files#32]
What viewer did you use to check geometry?
I see IFC geometry mismatch PNG

![image](https://user-images.githubusercontent.com/6941925/94371115-b0a08300-00fc-11eb-8d22-3bf0cf96e7ee.png)

![image](https://user-images.githubusercontent.com/6941925/94371126-c615ad00-00fc-11eb-86bc-1f9ee6def7d6.png)

**Comment by I-Sokolov** [comment]
@LeeGregory12d, @pjanck any responce?

**Comment by LeeGregory12d** [comment]
Sorry I do have replacement files with different images to show more detail.
But I'm just trying to figure out how I've screwed up GitHub.

**Comment by pjanck** [comment]
Either something changed in between or it is a problem on your end, @I-Sokolov (disregard the random coloring). Care to double check on your end?

![grafik](https://user-images.githubusercontent.com/59165496/98704975-8853a780-237d-11eb-9b46-4a575b8a5887.png)

**Comment by pjanck** [comment]
Closing the issue since no action for 2 months.
