### ISSUE TITLE
UT_tiny_tin_in_MGA_56: mismatch geometry, coordinates are wrong

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/Sample-Test-Files#33]
What IFC viewer did you use to verify IFC?
I see geometry mismatch PNG and coordinate values exceed 7000 km

    #31 = IFCCARTESIANPOINTLIST3D(((260978.300857938, **7007098.22119578,** 0.),

![image](https://user-images.githubusercontent.com/6941925/94371434-37565f80-00ff-11eb-8edf-253023489aae.png)

**Comment by TLiebich** [comment]
We should discourage the use of GIS coordinates (more then 20-50km away from the origin), so this UC should be combined with the UC georef to offset the coordinate values.

**Comment by I-Sokolov** [comment]
@LeeGregory12d, @pjanck any responce?

**Comment by LeeGregory12d** [comment]
Sorry I do have replacement files with different images to show more detail.
But I'm just trying to figure out how I've screwed up GitHub.

**Comment by LeeGregory12d** [comment]
Thomas,
All infrastructure jobs are done is GIS coordinates.

**Comment by pjanck** [comment]
I think this goes well with the discussion in #38 . I think that using `IfcMapConversion` to reduce the values of GIS coordinates should be considered. 

@LeeGregory12d : this does not invalidate that the model is in MGA. 

@TLiebich I agree that each infrastructure model should include/build upon the GeoRef UT.

**Comment by pjanck** [comment]
It was agreed that "big" coordinates do not make an IFC file wrong. It is a limit of the reading software.
