### ISSUE TITLE
IfcLinearSpanPlacement deprecated - how to represent From-To span like situation

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/Sample-Test-Files#52]
Discussing with @seb-esser regarding #25 :

1. `IfcLinearSpanPlacement` is deprecated with IFC4x3_RC2 (see [here](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifclinearspanplacement.htm))
2. Scenario:
  - Alignment designer (AD) --> bridge designer (BD)
  - AD has an alignment straight (100m) - circular curve (100m) = sum(200m)
  - AD plans a bridge starting at 37m and finishing at 166m - the bridge starts/ends somewhere along the alignment's segments
  - AD is in an early design phase where he wishes to exchange this information with the BD that will then construct the bridge - there isn't any geometrical information yet, except for the alignment. 
3. Which entities to use for this exchange?

**Comment by pjanck** [comment]
Would that be the correct solution? (Legend: colors mean nothing, names are shortened as need be - please take the sketch *cum grano salis*)

![grafik](https://user-images.githubusercontent.com/59165496/98918233-a7614f00-24cd-11eb-8716-3fe7c9c44fe6.png)

**Comment by larswik** [comment]
I just had a discussion with the Finnish storyline team about this (Juha + Juha) and they could understand why it was deprecated as a kind of placement but they also wanted to know how to do this thing instead of using IfcLinearSpanPlacement since it is a convenient way for infra to specify when something happens along a segment of an alignment. I think that we need a good example for this.  The "Span" does not have to start and end where the "defining" segments for the alignment starts and ends.

**Comment by jmirtsch** [comment]
I agree with Stefan, a segment curve is how I'd "represent" the conceptual bridge.

I've added a conceptual bridge to my work in progress alignment example at https://github.com/jmirtsch/testIfcAlignment

![201113 conceptual bridge curve segment](https://user-images.githubusercontent.com/791757/99028622-4ff1da80-25c4-11eb-90d0-800bf96fd8a5.png)

[test_TfNSW.zip](https://github.com/buildingSMART/Sample-Test-Files/files/5534741/test_TfNSW.zip)

If anyone has suggestions or feedback on this, I look forward to hearing them.  Note the curve segment can trim a curve at any distance, not constrained to alignment segment extremities.

**Comment by seb-esser** [comment]
In my personal point of view, it seems a bit odd to have a local placement for the bridge (global or local coordinate system?) and then referencing a curve as the representation. The (partial) curve is not the shape or visualization of the bridge, it has the character of "where to find the bridge when driving along the given line". I understand that we can represent the desired scenario, but IMO it is way more complicated than before (as placement/location and representation get mixed more and more). Maybe someone can clarify my lack of understanding by providing me an instance diagram?

**Comment by SergejMuhic** [comment]
IfcFacility - contains - IfcLinearElement.Representation('Axis'). The geometric items can be any IfcCurve.

**Comment by seb-esser** [comment]
ready to close @pjanck ? I've recently pushed a major update to the spanAnnotation sample (thanks again to @jmirtsch for helping me out).
