### ISSUE TITLE
Choosing the correct SpatialStructure entities for infra projects

### ISSUE THREAD

**Issue by seb-esser** [buildingSMART/Sample-Test-Files#63]
The usage of `IfcFacility`, `IfcFacilityPart`, and corresponding subclasses `IfcRoad`, `IfcRailway`, `IfcBuilding`, `IfcBuildingStorey` etc. 
More specifically, the schema definition of `IfcFacility` might need clarifications to ensure consistent interpretation. 

Links: 
[IfcSpatialStructureElement](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifcspatialstructureelement.htm)
[IfcFacility](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifcfacility.htm)

![grafik](https://user-images.githubusercontent.com/56266373/100062562-0e68f700-2e30-11eb-891a-bf7c7b00de65.png)

**Comment by AlexBrad1ey** [comment]
Yes, I seems to need a clarification. as it is not Defined as Abstract

The intent of IfcFacility, (in addition to IfcBuiltElement becoming instantiable replacing IfcBuildingElementProxy) is to provide the catch all function for spatial elements not covered by the more specific subtypes, the the typing of the facility should be encoded under the ObjectType property of the entity. The specific subtype and relevent PDT or custom type should be used unless this is semantically incorrect, in which case IfcFacility is the appropriate object.

e.g. currently there is no Facility covering an Airport Complex/Facility therefore an IfcFacility named 'Some Airport' with ObjectType: AIRPORT would be the most suitable encoding.

**Comment by SergejMuhic** [comment]
There are a lot more issues like that. Some of these issues are broken documentation from IFC4x2, some of it is broken new documentation. Since you complained @seb-esser I have corrected the two mentioned entities :D but I will not devote more time to the rest. Pushed to IFCRail/IFC-Repository-Sandbox. Not sure if you have access.
