### ISSUE TITLE
Is a river an IfcMarineFacility instance?

### ISSUE THREAD

**Issue by seb-esser** [buildingSMART/Sample-Test-Files#64]
In #24, a first example assembling a road, a river, and a bridge was submitted for review. However, I am wondering how to model the logical unit of a river with a subtype of [IfcSpatialStructureElement](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifcspatialstructureelement.htm). 
Should I use IfcMarineFacility? Or is there any better option?

**Comment by AlexBrad1ey** [comment]
A River has 2 components a Spatial one and a Physical one.

In Spatial terms a river is a Managed Facility/Asset in the same way a stretch of Road is. therefore Rivers should be encoded at minimum as IfcMarineFacility.WATERWAY, more specific options include CANAL or NAVIGATIONALCHANNEL depending on its function. further breakdown can use IfcFacilityPart.SEGMENT and any of the common logitudinal infrastructure PDTs. there are also a collection of water related vertical level options such as LOWWATERLINE, WATERLINE or HIGHWATERLINE.

In Physical terms this brings in some of the new geotechnical entities. most notabily IfcWaterStratum that represents the physical volume of water within the river as a volume or a surface represntation. this is then grouped with a IfcSolidStratum with geometrics for the surface representation of the bank and the river bed. these to physical elements would be contained within the IfcFacility or FacilityPart defined above.
