### ISSUE TITLE
Requesting improvements in documentation of IfcRelInterferesElements

### ISSUE THREAD

**Issue by seb-esser** [buildingSMART/Sample-Test-Files#68]
I am trying to resolve #64 and #24  implementing `IfcRelIntereferesElements` and found the attribute definition: 
![grafik](https://user-images.githubusercontent.com/56266373/100867862-11e92780-349b-11eb-9b75-136117604db6.png)

Apparently an encoding issue. Shouldn´t this be a separated Enum ensuring the correct usage of ``PassesUnder` `PassesOver` etc.? I am wondering if I should use upper case style or any other writing style here (camelCase, ...). Likely there is an additional page in the documentation that clarifies my concerns. Thus, any guidance is appreciated 

@pjanck @SergejMuhic @jmirtsch @AlexBrad1ey any idea? Thanks in advance!

Link: **[IfcRelInterferesElements](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC2/HTML/link/ifcrelinterfereselements.htm)

**Comment by AlexBrad1ey** [comment]
InterferenceType is an existing property from previous IFC versions so we didnt want to restrict it to an enum. i'm not sure if it is elaborated in the documentation but as the attribute description says i would use the camel case style as defined. cant really use a where rule either as this would still restrict the content that would break the point of the property.

**Comment by TLiebich** [comment]
InterferenceType was defined as a string by purpose, since there was no final agreement about a finitive list of enumerators.
