### ISSUE TITLE
IfcAlignmentHorizontalSegment - positive vs negative radii

### ISSUE THREAD

**Issue by larswik** [buildingSMART/Sample-Test-Files#91]
StartRadiusOfCurvature is defined as "For a NONLINEAR horizontal segment type the radius of the curve at the start point (Placement of the segment). For CIRCULAR type it is constant i.e. StartRadiusOfCurvature and EndRadiusOfCurvature are always the same. For LINE type, both StartRadiusOfCurvature and EndRadiusOfCurvature is 0. If the radius is 0 it shall be interpreted as INFINITE."
Could a definition regarding the meaning of positive vs negative radii be added to the definition (clockwise/anti clockwise)?

**Comment by SergejMuhic** [comment]
Sure. I have added the following "Positive values imply a CCW direction whereas negative CW." to both Start and End. If this is clear enough, please mark this as resolved.

**Comment by SergejMuhic** [comment]
@larswik, if you are happy with the proposed text, please close this issue.

**Comment by larswik** [comment]
I'm happy :-)
