### ISSUE TITLE
IfcAlignmentVerticalSegment - Gradient is an IfcLengthMeasure?

### ISSUE THREAD

**Issue by pjanck** [buildingSMART/Sample-Test-Files#92]
I must have missed a discussion somewhere. What is the rationale that the `IfcAlignmentVerticalSegment.Gradient`s are expressed as IfcLengthMeasure?

*EDIT: markdown syntax*

**Comment by SergejMuhic** [comment]
Should be IfcRatioMeasure, shouldn't it?

**Comment by pjanck** [comment]
Well, yes. I think. Looking at the changes from IFC4x3_RC1, it was an `IfcRatioMeasure`:

![grafik](https://user-images.githubusercontent.com/59165496/104885310-25c3ec80-5968-11eb-9959-2e39d7005d20.png)

**Comment by SergejMuhic** [comment]
Thanks, will correct.

**Comment by TLiebich** [comment]
Hi all - I had reported this issue before (I checked, it was in the IFC Rail Sandbox). So obviously, there are different places to report IFC4.3 RC2 issues - lets agree on ONE place to offically log requests to schema and documentation changes.

How about here?
[https://github.com/buildingSMART/IFC4.3.x-development/issues](https://github.com/buildingSMART/IFC4.3.x-development/issues)

**Comment by TLiebich** [comment]
and don't forget to also change EndGradient

**Comment by SergejMuhic** [comment]
> and don't forget to also change EndGradient

This is done. Thanks for thinking about it.

**Comment by SergejMuhic** [comment]
> Hi all - I had reported this issue before (I checked, it was in the IFC Rail Sandbox). So obviously, there are different places to report IFC4.3 RC2 issues - lets agree on ONE place to offically log requests to schema and documentation changes.
> 
> How about here?
> https://github.com/buildingSMART/IFC4.3.x-development/issues

Would be good but I would prefer here: https://github.com/buildingSMART/IFC/issues as it features the entire baseline, not just a part. Also, we will be merging all the changes from alignment into this repo.

**Comment by TLiebich** [comment]
I could go for either of the two. Seems we need a policy here @berlotti ?

**Comment by SergejMuhic** [comment]
Corrected.
