### ISSUE TITLE
IfcAlignmentVerticalSegment.StartDistAlong value documentation

### ISSUE THREAD

**Issue by larswik** [buildingSMART/Sample-Test-Files#94]
I think that the documentation is not crystal clear whether the IfcAlignmentVerticalSegment.StartDistAlong value shall include IfcAlignmentHorizontal or not? See unit test UT_Alignment_12d_8.

**Comment by SergejMuhic** [comment]
I am not sure I understand. But let me give it a shot:
- IfcAlignmentHorizontal.StartDistanceAlong just gives information about the start measuring value, so, at the start, the station should be 1000
- IfcAlignmentVerticalSegment.StartDistAlong is an actual measure along horizontal

That being said, could you point me to the ambiguity? Is there a proposal for a change?

**Comment by TLiebich** [comment]
current semantic definition of _IfcAlignmentVerticalSegment.StartDistAlong_ says (RC2):

StartDistAlong | IfcLengthMeasure |   | Distance along the horizontal alignment, measured along the IfcAlignment2DHorizontal given in the length unit of the global IfcUnitAssignment.

it requires modification - would propose:

Distance along the horizontal alignment as measured along the corresponding _IfcAlignmentHorizontal_.

NOTE 1: the distance along is measured from the start point of the _IfcAlignmentHorizontal_, any eventually provided offset expressed by _IfcAlignmentHorizontal.StartDistanceAlong_ is not taken into account.

NOTE 2: the unit of measurement is the global length unit, as set by _IfcContext.UnitInContext_

**Comment by SergejMuhic** [comment]
Thanks @TLiebich. Note 1 should be quite clear on the issue. Good thinking about Note 2. @larswik is this okay with you? Please close the issue and I will incorporate it into the documentation.

**Comment by larswik** [comment]
Sorry for my fuzzy comment. The comment was regarding whether IfcAlignmentHorizontal.**StartDistAlong** should be taken into account or not. Thank you @TLiebich for clarifying. I think that the proposal is very clear! Closing the issue.
