### ISSUE TITLE
IfcAlignmentVertical starts before and/or ends after IfcAlignmentHorizontal

### ISSUE THREAD

**Issue by larswik** [buildingSMART/Sample-Test-Files#95]
See UT_Alignment_12d_10 and 11 (https://github.com/buildingSMART/Sample-Test-Files/pull/82 and https://github.com/buildingSMART/Sample-Test-Files/pull/83). Maybe this needs discussion/clarification?

**Comment by pjanck** [comment]
`IfcAlignmentVertical.StartDistAlong` is a `IfcLengthMeasure`, so it can have negative values - meaning starting before the start of `IfcAlignmentHorizontal` (see also #94 ). Similarly for the ending.
