### ISSUE TITLE
Structure of IfcAlignment 4x3RC2 in the sematic and geometry part

### ISSUE THREAD

**Issue by BernhardWehrle** [buildingSMART/Sample-Test-Files#98]
Hello everybody
I created a unit test for the IfCourse object.
Since there are some problems with IfcAlignment (IfcAlignmentCurve is deprecated).
Is there a complete documentation and diagrams about the exact structure of IfcAlignment 
in the semantic and geometry part for IFC4.3 RC2.

What should I use instead IfcAlignmentCurve.
In the moment its very difficult to find the right way
to implement the IfcAlignment.
A diagramm with semantic und geometric part
of the Alignment in Ifc4x3RC2 would be very helpful

**Comment by pjanck** [comment]
Currently discussing here: https://forums.buildingsmart.org/t/ifc-development-monthly-call-scheduled-topics/2713

![grafik](https://user-images.githubusercontent.com/59165496/105370429-def22300-5c03-11eb-865a-3ca5f3cac1c0.png)

Hopefully this helps you at least a bit.

**Comment by pjanck** [comment]
We're moving to the new repository. If you're still having difficulties, be sure to open a new issue there: https://github.com/bSI-InfraRoom/IFC-infra-unit-test
